# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "SpinalTapCodeMosh"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    Database:
        driver:   SQLite
        database: 'db/mosh.sqlite'

# Setting this will display an "Announce to IRC" box on the new mosh form.
# STCM will "GET" the specified URL with the params channel and message upon
# submission with the Announce to IRC option checked.
IRC:
    url:      'http://my_irc_web_hook/'            # IRC Webhook URL.
    message:  'New Mosh by $poster: $url - $title' # The message that will be posted to the channel via the webhook
    channels: [ mychannel, anotherchannel ]        # A list of channel options that will be presented in the new mosh form.

